### ISSUE TITLE
Usage guide?

### ISSUE THREAD

**Issue by TrebuhD** [ramiel/redux-persist-nextjs#1]
I took a look at the code, but it's still not clear to me how to integrate this into a next.js app. Do you think you could provide some basic guide?

**Comment by ramiel** [comment]
Hey, I'm looking at this repository and I don't even remeber what it was about. Usually my repos have a complete readme and everything so it's probably something personal used for some other project. I'll remove this repo when I'm sure there is no code relying on it. Sorry.
